name: Run Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3

      - name: Debug Filesystem
        run: ls -R $(pwd)

      - name: Node.js einrichten
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Installiere Abhängigkeiten
        run: |
          npm ci
          npm install express

  run-tests:
    runs-on: ubuntu-latest
    needs: install-dependencies  # Erst starten, wenn "install-dependencies" abgeschlossen ist
    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3

      - name: Starte den Webserver
        run: |
          nohup node $(pwd)/server.js &
          sleep 10 # Warte 10 Sekunden, bis der Server gestartet ist

      - name: Warte auf den Server
        run: |
          npx wait-on http://localhost:3000 --timeout 60000
          echo "Server is ready"

      - name: Führe Tests mit Jest & Puppeteer aus
        run: npm test

      - name: Testberichte hochladen
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: test-results/