name: Run Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3

      - name: Installiere Abhängigkeiten
        run: |
          npm install
          npm install --save-dev wait-on
          npm install express

  run-tests:
    runs-on: ubuntu-latest
    needs: install-dependencies  # Erst starten, wenn "install-dependencies" abgeschlossen ist
    steps:
      - name: Starte den Webserver
        run: npm start > server.log 2>&1 &

      - name: Logdatei ausgeben
        run: cat server.log

      - name: Warte auf den Server
        run: |
          sleep 5  # Warte kurz, damit der Server Zeit hat zu starten
          curl -Is http://localhost:3000 || echo "Server nicht erreichbar!"

      - name: Warten, bis der Server bereit ist
        run: npx wait-on http://localhost:3000 --timeout 60000

      - name: Führe Tests mit Jest & Puppeteer aus
        run: npm test

      - name: Testberichte hochladen
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: test-results/