name: Run Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Repository auschecken
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Installiere Abhängigkeiten
        run: |
          npm install
          npm install --save-dev wait-on
          npm install express

  run-tests:
    runs-on: ubuntu-latest
    needs: install-dependencies  # Erst starten, wenn "install-dependencies" abgeschlossen ist
    steps:
      - name: Starte den Webserver
        run: |
          nohup node server.js &
          sleep 10 # Warte 10 Sekunden, bis der Server gestartet ist

      - name: Warte auf den Server
        run: |
          wait-on http://localhost:3000 --timeout 60000
          echo "Server is ready"

      - name: Führe Tests mit Jest & Puppeteer aus
        run: npm test

      - name: Testberichte hochladen
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: test-results/